name: Automate Weather Script

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 AM
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run weather script
      run: ./weather.sh

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Automated weather data update'
        git push
