name: Run Stocks Script and Push changes

on:
    schedule:
       # Runs daily at 10:00 AM UTC
        - cron: '0 10 * * *'
    workflow_dispatch:


jobs:
    run-stocks-script:
        runs-on: ubuntu-latest
        
        steps:
        # Step 1: Check out the repository
            - name: Checlout repository
                 uses: actions/checkout@v3

        # Step 2: Set up Python
            - name: Set up Python
                 uses: actions/steup-python@v4
                 with:
                      python-version: '3.x' 
                      
         # Step 3: Install dependencies             
            - name: Install dependencies
                 run: |
                    python -m pip install --upgrade pip
                    pip install -r requeriments.txt

            - name: Run stocks.py
                 run: python stocks.py
